version: 0.2

phases:

  install:
    commands:
      - pip install pybuilder
    finally:
      - echo "Installed pip packages"
      - pip list
  pre_build:
    commands:
      - |
        if [ -d ".giit" ]; then
          export GIT_DESCRIBE=A
          echo "Version gitdescribed"
        elif [ -z ${CODEBUILD_RESOLVED_SOURCE_VERSION+x} ]; then
          export GIT_DESCRIBE="unknown"
          echo "Version unknown"
        else
          export GIT_DESCRIBE=B
          echo "Version codebuilded"
        fi
      - export PROJECT_NAME=$(python -c "import build; build.print_name()")
  build:
    commands:
      - pyb -v clean install_dependencies run_unit_tests package
  post_build:
    commands:
      - find target/
    finally:
      - printenv
artifacts:
  files:
    - ./**/*
  name: $PROJECT_NAME-$GIT_DESCRIBE
  base-directory: target/dist/
  discard-paths: no

