version: 0.2

phases:
  install:
    commands:
      - pip install pybuilder
    finally:
      - echo "Installed pip packages"
      - pip list
  pre_build:
    commands:
      - export PROJECT_NAME=$(python -c "import build; build.print_name()")
  build:
    commands:
      - pyb -v clean install_dependencies run_unit_tests package
  post_build:
    commands:
      - find target/
artifacts:
  files:
    - '**/*'
  name: ${PROJECT_NAME}-${PROJECT_VERSION}
  base-directory: target/dist/
  discard-paths: no

