version: 0.2

phases:
  install:
    commands:
      - pip install pybuilder pylint
    finally:
      - echo "Installed pip packages"
      - pip list
  pre_build:
    commands:
      - PROJECT_NAME=$(python -c "import build; print(build.name))
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - PACKAGE_LOCATION=target/dist/
      - PACKAGE_NAME=${PACKAGE_LOCATION}$(python -c "import build; print(build.name))-$(python -c "import build; print(build.version))/
  build:
    commands:
      - pyb -v clean install_dependencies run_unit_tests analyze package
  post_build:
    commands:
      - tarballing ${PACKAGE_NAME}
      - ARTIFACT_ZIP=artifact.tar.gz
      - tar -czvf ${ARTIFACT_ZIP} ${PACKAGE_NAME}
artifacts:
  files: artifact.tar.gz

