version: 0.2

phases:
  install:
    commands:
      - echo Abc = ${Abc}
      - pip install pybuilder pylint
    finally:
      - echo "Installed pip packages"
      - pip list
  pre_build:
    commands:
      - PROJECT_NAME=$(python -c "import build; print(build.name)")
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - PACKAGE_PATH=target/dist/${PACKAGE_LOCATION}$(python -c "import build; print(build.name)")-$(python -c "import build; print(build.version)")/
  build:
    commands:
      - pylint --rcfile=pylintrc src/main/python/
      - pyb -v clean install_dependencies analyze package
  post_build:
    commands:
      - echo tarballing ${PACKAGE_PATH}
      - ARTIFACT_ZIP=raqc.tar.gz
      - tar -C ${PACKAGE_PATH} -czvf ${ARTIFACT_ZIP} .
artifacts:
  files:
    - raqc.tar.gz
    - requirements.txt
    - Docker/Dockerfile
    - Docker/buildspec.yml
  discard-paths: yes