version: 0.2

phases:

  install:
    commands:
      - pip install pybuilder
    finally:
      - echo "Installed pip packages"
      - pip list
  pre_build:
    commands:
      - |
        if [ -d ".git" ]; then
          export GIT_DESCRIBE=${git describe}
          echo "Version gitdescribed"
        elif [ -z ${CODEBUILD_RESOLVED_SOURCE_VERSION+x} ]; then
          exit 42
        else
          export GIT_DESCRIBE=0.0.dev0-g${CODEBUILD_RESOLVED_SOURCE_VERSION:0:7}
          echo "Version codebuilded"
        fi
      - export PROJECT_NAME=$(python -c "import build; build.print_name()")
  build:
    commands:
      - pyb -v clean install_dependencies run_unit_tests package
  post_build:
    commands:
      - find target/
    finally:
      - printenv
artifacts:
  files:
    - ./**/*
  name: $PROJECT_NAME-$GIT_DESCRIBE
  base-directory: target/dist/
  discard-paths: no

