#!/usr/bin/env bash
MYPATH=$1
MYPATH="$(pwd)/${MYPATH}"
DOCKERP="${MYPATH}/Docker"
SOFTWAREP="${MYPATH}/software"
TMPF="${MYPATH}/temp_makemyday"

rm -rf ${TMPF}
mkdir ${TMPF}


cd ${SOFTWAREP}
pyb clean package
## DISTNAME name of current build as by pyb
DISTNAME=$(ls target/dist/)
## DISTFOLDER absolute folder into created dist
DISTFOLDER="target/dist/${DISTNAME}"
DISTFOLDER=${SOFTWAREP}/${DISTFOLDER}

DIST_TARBALL="${TMPF}/${DISTNAME}.tar.gz"

tar -zcvf ${DIST_TARBALL} -C ${DISTFOLDER} .


mkdir -p ${DOCKERP}/base/resources/
cp ${DIST_TARBALL} ${DOCKERP}/base/resources/app.tar.gz
docker build -t marvinlwenzel/raqcrawl ${DOCKERP}/base

mkdir -p ${DOCKERP}/test/resources/
declare -a TEST_RES=("src" "requirements.txt" "requirements-dev.txt" "build.py")

for i in "${TEST_RES[@]}"
do
    cp -r ${SOFTWAREP}/${i} ${DOCKERP}/test/resources/
done

docker build -t marvinlwenzel/raqcrawl-test ${DOCKERP}/test

rm -rf ${TMPF}